### PR TITLE
[ci:component:github.com/gardener/machine-controller-manager-provider-azure:v0.2.0->v0.3.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
**Release Notes*:
``` noteworthy user github.com/gardener/machine-controller-manager-provider-azure #23 @prashanth26
Fixes regressions while fetching Azure CSI PersistentVolumes during the eviction of Pods with PersistentVolumes.
```

### CODE REVIEW

**Review by prashanth26 — APPROVED** [review]
This PR fixes regressions while fetching volume details while draining CSI volumes attached to a node. Without this will affect gardener clusters of `v1.21.0` and above.

/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

/assign @kon-angelo

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
