### PR TITLE
Vendor g/g 1.20.0 to enable strict decoding of some resources

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority 3
/platform gcp

**What this PR does / why we need it**:
* Vendors g/g 1.20.0 (includes https://github.com/gardener/gardener/pull/3804) to ensure that a strict decoder is used also for `ControlPlaneConfig` and `WorkerConfig`, and errors are correctly categorized.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-azure/pull/270, see also https://github.com/gardener/gardener-extension-provider-azure/pull/271

**Special notes for your reviewer**:

**Release note**:

```breaking user
Extension resource configs (`ControlPlaneConfigs`, `WorkerConfig`) are now deserialized in "strict" mode. This means that deserializing resources with fields that are not allowed by the API schema will result in errors. Shoots containing such resources will fail with an appropriate error until you manually update the shoot to make sure any extension resource configs contained in it are valid.
```

### CODE REVIEW

**Review by ialidzhikov — CHANGES_REQUESTED** [review]
The TestDefinitions need an update as well.

```diff
diff --git a/.test-defs/infrastructure-test.yaml b/.test-defs/infrastructure-test.yaml
index 3570dec2..d698668a 100644
--- a/.test-defs/infrastructure-test.yaml
+++ b/.test-defs/infrastructure-test.yaml
@@ -18,4 +18,4 @@ spec:
       --client-secret=${CLIENT_SECRET}
       --region=${REGION}

-  image: eu.gcr.io/gardener-project/3rd/golang:1.15.7
+  image: eu.gcr.io/gardener-project/3rd/golang:1.16.3
diff --git a/.test-defs/provider-azure.yaml b/.test-defs/provider-azure.yaml
index 689b3232..6eb4dfc3 100644
--- a/.test-defs/provider-azure.yaml
+++ b/.test-defs/provider-azure.yaml
@@ -15,4 +15,4 @@ spec:
     --network-vnet-cidr=$NETWORK_VNET_CIDR
     --network-worker-cidr=$NETWORK_WORKER_CIDR
     --zoned=$ZONED
-  image: eu.gcr.io/gardener-project/3rd/golang:1.15.7
+  image: eu.gcr.io/gardener-project/3rd/golang:1.16.3
```

**Comment by stoyanr** [comment]
> The TestDefinitions need an update as well.

Done

**Comment by rfranzke** [comment]
Can you please revendor the `v1.20.0` tag now that it's released?

**Comment by stoyanr** [comment]
@rfranzke Done

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Thanks @stoyanr, can you check why the `verify` step is failing?

**Review by dkistner — APPROVED** [review]
/lgtm

**Comment by vpnachev** [comment]
> Thanks @stoyanr, can you check why the `verify` step is failing?

This is because the verify step is using golang 1.15 https://github.com/gardener/gardener-extension-provider-azure/blob/f5d1acc25f3546178ae369fc2b7237742db155e6/branch.cfg#L38

**Comment by rfranzke** [comment]
Thanks @vpnachev, then I guess we can go ahead and force-merge now?

**Comment by vpnachev** [comment]
> Thanks @vpnachev, then I guess we can go ahead and force-merge now?

I think we can firstly update the pipeline with golang 1.16, re-run the validation and merge it gracefully.

**Pull request merged**
