### PR TITLE
Update default storage account SKU to StandardZRS

### PR DESCRIPTION
**Pull request by seshachalam-yv**
**How to categorize this PR?**

/area storage
/kind enhancement
/platform azure

**What this PR does / why we need it**:
This PR updates the default storage account SKU and Kind in the Azure extension. The changes are as follows:
- SKU: StandardLRS to StandardZRS
- Kind: BlobStorage to StorageV2

The change enhances data durability and availability by leveraging Zone Redundant Storage (ZRS), which replicates data across multiple availability zones.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Updated the default storage account SKU from StandardLRS to StandardZRS to enhance data durability and availability.
```

### CODE REVIEW

**Review by shreyas-s-rao — APPROVED** [review]
@seshachalam-yv thanks for the PR. 

/lgtm

**Comment by shreyas-s-rao** [comment]
/ping @gardener/gardener-extension-provider-azure-maintainers

**Comment by ishan16696** [comment]
Hi @gardener/gardener-extension-provider-azure-maintainers,
This is the high priority PR, please review this and get this PR merge and please include this PR in next upcoming release.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
