### PR TITLE
Handle user related error code at missing place in infra deletion flow

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area ops-productivity
/kind regression
/platform azure

**What this PR does / why we need it**:
Check motivation for this PR -> https://github.com/gardener/gardener-extension-provider-azure/issues/660

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardener-extension-provider-azure/issues/660

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
An issue causing Azure-related errors not getting categorized properly is now fixed.
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I created https://github.com/gardener/gardener-extension-provider-azure/issues/662 to cover this scenario with integration test.

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
