### PR TITLE
Ensure remedy controller resources have been deleted

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**
/area control-plane
/kind enhancement
/priority normal
/platform azure

**What this PR does / why we need it**:
Ensures that all remaining remedy controller resources have been deleted before deleting the remedy controller itself.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/remedy-controller/issues/32

**Special notes for your reviewer**:

**Release note**:
```improvement operator
The controlplane controller now ensures that all remaining remedy controller resources have been deleted before deleting the remedy controller itself.
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @stoyanr for your contribution. I will start a build for your PR. Once started, the build URL will be posted here.

**Comment by gardener-robot-ci-3** [comment]
A build of this pull request has started. You can check on its progress here: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-azure-master/jobs/master-pull-request-job/builds/3

**Comment by gardener-robot-ci-3** [comment]
Thank you @stoyanr for updating the PR. I will start a build. Once started, the build URL will be posted here.

**Comment by gardener-robot-ci-1** [comment]
A build of this pull request has started. You can check on its progress here: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-azure-master/jobs/master-pull-request-job/builds/4

**Comment by AndreasBurger** [comment]
So if I understand this correctly, part of the Remedy Controller is now vendored in here so that we can enhance the extension-provider to also clean up after the Remedy Controller.
On the one hand, I don't like the coupling of both components. On the other, I think this a pragmatic approach.

**Comment by rfranzke** [comment]
@AndreasBurger The components are not coupled, or rather, what you mean with "coupled" is already in place without this PR. The Azure extension deploys the Azure remedy controller already with a specific version and a specific deployment manifest, so it already has knowledge about what the remedy controller will do.

**Comment by gardener-robot-ci-3** [comment]
Thank you @stoyanr for updating the PR. I will start a build. Once started, the build URL will be posted here.

**Comment by gardener-robot-ci-1** [comment]
A build of this pull request has started. You can check on its progress here: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-azure-master/jobs/master-pull-request-job/builds/5

**Comment by gardener-robot-ci-1** [comment]
Thank you @stoyanr for updating the PR. I will start a build. Once started, the build URL will be posted here.

**Comment by gardener-robot-ci-1** [comment]
A build of this pull request has started. You can check on its progress here: https://concourse.ci.gardener.cloud/teams/gardener/pipelines/gardener-extension-provider-azure-master/jobs/master-pull-request-job/builds/6

**Comment by stoyanr** [comment]
@rfranzke To add unit tests, I need to generate mocks for the `Actuator` interface in `gardener/gardener`, since such don't exist yet. I could do this, however this would mean we would need a new Gardener release with the mocks before we could release the new Azure extension. Do you think it's worth the trouble? If yes, I'll do it.

**Comment by stoyanr** [comment]
@rfranzke Here is the PR with the generated mocks that I need: https://github.com/gardener/gardener/pull/2644

**Comment by stoyanr** [comment]
@rfranzke I also need #2645 (same as #2644 but for v1.7), since rebasing the Azure extension on top of master would involve a bigger rework.

**Comment by stoyanr** [comment]
Rebased on top of #141, dependency to https://github.com/stoyanr/gardener removed.

**Comment by stoyanr** [comment]
Rebased on top of master and removed "draft".

**Pull request merged**
