### PR TITLE
Add DNSRecord controller

### PR DESCRIPTION
**Pull request by stoyanr**
**How to categorize this PR?**

/area control-plane
/kind api-change
/kind enhancement
/platform azure

**What this PR does / why we need it**:
* Adds a Azure-specific implementation of a DNSRecord controller, see https://github.com/gardener/gardener/pull/4231.
* Vendors g/g v1.27.0-dev and k8s v0.21.2 (in a separate commit to make reviews easier)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Note the following important details:
* The provider type is `azure-dns` (like in `DNSProvider`), not `azure` (like in other controllers) for reasons of compatibility and ease of migration.

See also https://github.com/gardener/gardener-extension-provider-aws/pull/362 and https://github.com/gardener/gardener-extension-provider-aws/pull/370.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by rfranzke — COMMENTED** [review]
looks good, no comments after a high-level scan

**Review by MartinWeindel — DISMISSED** [review]
/lgtm

**Comment by stoyanr** [comment]
@rfranzke @MartinWeindel Rebased, and since there are no other comments, could you please give a formal approval so we could merge this PR?

**Review by MartinWeindel — APPROVED** [review]

**Review by dkistner — APPROVED** [review]
Looks good to me. Thank you.

**Pull request merged**
