### PR TITLE
Update usage-as-end-user.md

### PR DESCRIPTION
**Pull request by jbasement**
Only added one missing word, so no description needed

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @jbasement for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by dkistner — COMMENTED** [review]
/lgtm

**Review by rfranzke — APPROVED** [review]
/reviewed ok-to-test
/lgtm

@jbasement please sign the CLA

**Comment by jbasement** [comment]
@rfranzke Done 👍

**Pull request merged**
