### PR TITLE
bump prometheus/client_golang

### PR DESCRIPTION
**Pull request by FriedrichWilken**
this PR bumps `github.com/prometheus/client_golang` and `sigs.k8s.io/controller-runtime` to `v0.11.1`.

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @FriedrichWilken for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by rfranzke** [comment]
`make revendor`

**Review by rfranzke — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
same as https://github.com/gardener/gardener-extension-provider-azure/pull/497#issuecomment-1120750297 here
/close

**Pull request closed without merging**
