### PR TITLE
Make the Azure Instance to connect to configurable

### PR DESCRIPTION
**Pull request by AndreasBurger**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform azure

**What this PR does / why we need it**:
Adds the option to configure the Azure instance the provider-extension connects to.

**Release note**:

```other operator
The Azure instance to connect to can now be configured in the CloudProfile and BackupBucket/BackupEntry.
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — DISMISSED** [review]
/lgtm

**Comment by AndreasBurger** [comment]
Merging by overriding branch-protections as the successful TM-Checkresult was somehow discarded.

**Pull request merged**
