### PR TITLE
Update kubernetes-csi/external-snapshotter to v3.0.3

### PR DESCRIPTION
**Pull request by tareqhs**
**How to categorize this PR?**
/area storage
/kind enhancement
/platform azure

**What this PR does / why we need it**:
Upgrade csi snapshotter (external-snapshotter controller) to v3 to acquire bug fixes and improvements.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-csi/external-snapshotter/issues/349
The fix is available in v3 of external-snapshotter controller.

**Release note**:
```feature user
The following images are updated (see [CHANGELOG](https://github.com/kubernetes-csi/external-snapshotter/blob/v3.0.3/CHANGELOG/CHANGELOG-3.0.md) for more details):
- k8s.gcr.io/sig-storage/csi-snapshotter: v2.1.5 -> v3.0.3
- k8s.gcr.io/sig-storage/snapshot-controller: v2.1.5 -> v3.0.3
```

### CODE REVIEW

**Review by rfranzke — APPROVED** [review]
/lgtm
/needs second-opinion
/invite @ialidzhikov

**Comment by dkistner** [comment]
I also checked it and looks good to me.
But wanted to ask @ialidzhikov for his opinion before we merge it.

**Comment by tareqhs** [comment]
@ialidzhikov this is based on https://github.com/gardener/gardener-extension-provider-aws/pull/366

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
