### PR TITLE
Vendor gardener/gardener@v1.50.1 

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform azure

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency is updated:
- github.com/gardener/gardener: v1.48.0 -> v1.50.1
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
/lgtm

**Comment by dkistner** [comment]
re run `make generate` is required.

**Comment by acumino** [comment]
I guess it can be merged now.
/invite @kon-angelo

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
