### PR TITLE
Revendor `gardener/gardener@v1.40.1`

### PR DESCRIPTION
**Pull request by dkistner**
**How to categorize this PR?**
/kind enhancement
/platform azure
/merge squash
/milestone v1.26

**What this PR does / why we need it**:
Revendor `gardener/gardener@v1.40.1` dependency.
This will include an upgrade to `ginkgo` v2.

Substitution for https://github.com/gardener/gardener-extension-provider-azure/pull/438 (closed on accident)

**Release note**:
```other operator
NONE
```

### CODE REVIEW

**Comment by dkistner** [comment]
Integration test are failing due to missing permissions of the spn to create a managed identity.
/cc @donistz

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
