### PR TITLE
Vendor gardener/gardener 1.11.1

### PR DESCRIPTION
**Pull request by dkistner**
**How to categorize this PR?**

/area open-source
/kind task
/priority normal
/platform azure

**What this PR does / why we need it**:
Revendor gardener v1.11.1

**Release note**:

```improvement operator
`github.com/gardener/gardener` dependency is now updated to `v1.11.1`.
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
lgtm but `make generate` required again

**Comment by vpnachev** [comment]
Please, add `SKIP_FETCH_TOOLS=1` in the Makefile like it was proposed for the gcp extension [here](https://github.com/gardener/gardener-extension-provider-gcp/pull/183#pullrequestreview-506211653).

**Comment by dkistner** [comment]
fixed ci stuff.

**Review by kon-angelo — APPROVED** [review]

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
