### PR TITLE
Enable vm boot diagnostics

### LINKED ISSUE #786: Enable Serial Console Support in Worker Node
**How to categorize this issue?**

/area monitoring
/kind enhancement
/platform azure

**What would you like to be added**:
We would like Gardener to enable serial console from each worker node (VMs ) in Azure.
Currently serial console access is unavailable even with correct CAM permission.   

**Why is this needed**:

The serial console would allow easier debug/operational process and would significantly decrease development time.

### PR DESCRIPTION
**Pull request by hebelsan**
**How to categorize this PR?**

/area usability
/kind enhancement
/platform azure

**What this PR does / why we need it**:

- Add support to enable vm boot diagnostics in the worker providerConfig

**Which issue(s) this PR fixes**:
Fixes #786 

**Special notes for your reviewer**:

**Release note**:

```feature user
Extension-Provider-Azure now supports enabling of vm boot diagnostics in the worker providerConfig.
```

### CODE REVIEW

**Comment by hebelsan** [comment]
I would like to add an e2e test, but therefore this [PR in mcm azure](https://github.com/gardener/machine-controller-manager-provider-azure/pull/136) must be merged first.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
