### PR TITLE
Support for Kubernetes v1.21 + CSI migration

### LINKED ISSUE #3: Adopt CSI for Azure extension beginning with Kubernetes 1.21
As of Kubernetes 1.18 the in-tree Azure Disk volume driver is deprecated in favour of CSI. We should adopt CSI for 1.18+ clusters (where the Azure Disk migration will be promoted to beta as well)

See also: https://github.com/kubernetes/kubernetes/pull/85231 and https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source usability
/kind enhancement
/priority 3
/platform azure
/exp intermediate
/topology garden seed shoot

**What this PR does / why we need it**:
This PR adds support for 1.21 to the extension and also support for CSI (+ migration for existing clusters).
CSI will be used for 1.21 shoots. Older shoots will keep using the in-tree legacy volume provisioners.

**Which issue(s) this PR fixes**:
Part of gardener/gardener#3851
Fixes #3

**Special notes for your reviewer**:
* :white_check_mark: Depends on gardener/gardener#3860
* I have successfully validated the functionality as follows:
  * :white_check_mark: Create new clusters with versions < 1.21
  * :white_check_mark: Create new clusters with version  = 1.21
  * :white_check_mark: Upgrade old clusters from version 1.20 to version 1.21
  * :white_check_mark: Delete clusters with versions < 1.21
  * :white_check_mark: Delete clusters with version  = 1.21

**Release note**:

```action user
The Azure extension does now support shoot clusters with Kubernetes version 1.21. You should consider the [Kubernetes release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md) before upgrading to 1.21. Please note that both the Azure Disk CSI driver and Azure File CSI driver will be used for 1.21 shoots. They are compatible with the legacy volume provisioners, however, you might want to update your storage classes and volume handling accordingly. Please find more information about CSI in the official Kubernetes documentation.
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
Thank you.
I played around with it. I can confirm cluster creation/deletion + migration does work well.
Also the CSI migration work nicely.

**Comment by rfranzke** [comment]
Should we merge then?

**Pull request merged**
