### PR TITLE
Vendor gardener/gardener@v1.11.1 without a hack

### PR DESCRIPTION
**Pull request by ialidzhikov**
**How to categorize this PR?**

/area quality
/kind bug
/priority normal
/platform azure

**What this PR does / why we need it**:
I ran `make revendor` on the master branch.

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by timebertt** [comment]
I was already thinking about adding a `make revendor` to `check-generate`, so that a build only succeeds if the vendor folder is correctly maintained.
@gardener/gardener-maintainers WDYT?

**Comment by ialidzhikov** [comment]
+1, that would be very nice

**Comment by vpnachev** [comment]
We can try it.

**Comment by timebertt** [comment]
Ref: https://github.com/gardener/gardener/issues/2979

**Pull request merged**
