### PR TITLE
Vendor `gardener/gardener@1.70.2` and adapt provider-extension for workerless `Shoot`

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform azure

**What this PR does / why we need it**:
- Vendor gardener `v1.70.2`
- Skip mutation and validation for shoots if it's workerless.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
The following dependency has been updated:
- github.com/gardener/gardener 1.67.1 -> 1.70.2
```

### CODE REVIEW

**Review by MartinWeindel — DISMISSED** [review]
/lgtm

**Comment by acumino** [comment]
/hold
for testing changes locally.

**Review by MartinWeindel — APPROVED** [review]
/lgtm

**Pull request merged**
