### PR TITLE
adopt nodeTemplate in MachineClasses

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**How to categorize this PR?**

/area auto-scaling
/kind enhancement
/platform azure

**What this PR does / why we need it**:
This PR adopts nodeTemplate field from the worker resource while creating the MachineClasses as needed by Cluster Autoscaler for a generic scale from zero.

**Which issue(s) this PR fixes**:
Fixes #[Autoscaler/#27](https://github.com/gardener/autoscaler/issues/27)

**Special notes for your reviewer**:
Gardener v1.38 & latest MCM must be vendored. Until then the build may fail.

**Release note**:

```feature user
NONE
```

### CODE REVIEW

**Comment by AxiomSamarth** [comment]
Thank you for the help, @kon-angelo!

**Comment by rfranzke** [comment]
What's the status of this pR?

**Comment by himanshu-kun** [comment]
The PR is ready, but since the changes will be same as that made in `extension-aws` so we would like to wait before merging this one, until the extension-aws gets deployed on live this Wednesday and no regressions are seen on Canary.
/hold

**Comment by himanshu-kun** [comment]
yes @rfranzke  its ready to merged now, all other such PRs on extension providers as well.

**Comment by rfranzke** [comment]
Thanks @himanshu-kun. @dkistner @kon-angelo Would you kindly take care of merging these PRs so that we can close the topic?

**Comment by dkistner** [comment]
Yes I have it on my list. Will soon have a look.
/assign

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
