### PR TITLE
Set PodDisruptionBudget maxUnavailable=1 in provider chart

### PR DESCRIPTION
**Pull request by gesslein**
**How to categorize this PR?**
/area robustness
/kind bug
/platform azure

**What this PR does / why we need it**:
I believe this should have been changed in #599 but was forgotten. In other extensions this was changed as well e.g.
https://github.com/gardener/gardener-extension-provider-openstack/blame/master/charts/gardener-extension-provider-openstack/templates/poddisruptionbudget.yaml#L13

This avoids nodes being unable to drain as the default replicaCount: 1 minus 1 is zero, even though gardener now runs the provider deployment with two replicas.

**Special notes for your reviewer**:
I don't think this requires release notes, if you think it does feel free to add some.

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @gesslein for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by kon-angelo — DISMISSED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — DISMISSED** [review]
/lgtm

**Comment by kon-angelo** [comment]
@gesslein you need to rerun `make generate` for the `controller-registration` file.

**Comment by gesslein** [comment]
Thanks, I've rebased and re-run make generate @kon-angelo

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
