### PR TITLE
[ci:component:github.com/gardener/terraformer:v2.15.0->v2.16.0]

### PR DESCRIPTION
**Pull request by gardener-robot-ci-3**
**Release Notes**:
``` other operator github.com/gardener/terraformer #107 @stoyanr
terraform has been upgraded to 0.15.5
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/hold
until v1.26 is released

**Comment by ialidzhikov** [comment]
/unhold
as v1.26.0 release is out

**Comment by kon-angelo** [comment]
We were giving some time for our landscapes to consume the last version. I think we can proceed with merging it now.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
