### PR TITLE
Automatically configure calico properly if ebpf dataplane is used.

### PR DESCRIPTION
**Pull request by ScheererJ**
**How to categorize this PR?**

/area networking
/area usability
/kind enhancement
/platform azure

**What this PR does / why we need it**:
Automatically configure calico properly if ebpf dataplane is used.

Azure accelerated networking introduces other network interfaces (enP...). Calico's ebpf dataplane needs to omit those interface. Otherwise, the traffic of those interfaces is effectively dropped. This change achieves it via a mutating web hook injecting an environment variable into calico's daemon set.

**Which issue(s) this PR fixes**:
None.

**Special notes for your reviewer**:
Previously, the [corresponding limitation](https://github.com/gardener/gardener-extension-networking-calico/blob/master/docs/usage/usage.md#know-limitations-of-the-ebpf-dataplane) was just documented. Now, it is automated so that cluster owners do not have to think about it anymore.
Please note that the web hook is registered for all clusters, i.e. regardless of the CNI and the specific settings of the CNI.

**Release note**:

```other operator
VM types with azure accelerated networking now work out-of-the-box with calico's ebpf dataplane.
```

### CODE REVIEW

**Comment by Garfield96** [comment]
@ScheererJ Thanks for implementing this useful feature. Are there any blockers preventing this PR from being merged?

**Comment by ScheererJ** [comment]
> @ScheererJ Thanks for implementing this useful feature. Are there any blockers preventing this PR from being merged?

@Garfield96 Only vacation season is blocking this pull request as far as I know. I hope that it will be merged by the end of September at the latest.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
