### PR TITLE
Add support for VolumeAttributesClasses

### PR DESCRIPTION
**Pull request by AndreasBurger**
**How to categorize this PR?**

/area storage
/kind enhancement
/platform azure

**What this PR does / why we need it**:
With this PR support for [volume attributes classes](https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/) is added by allowing to configure the necessary parameters for it to work.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by AndreasBurger** [comment]
I'll leave it on draft for now, until the corresponding GCP PR is approved since there will probably be some more changes depending on it.

Also, still needs a manual test-run.

**Comment by AndreasBurger** [comment]
Should be good, though not yet tested. Undrafted all the same

**Review by hebelsan — APPROVED** [review]
/lgtm

**Review by kon-angelo — DISMISSED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]

**Pull request merged**
